appName: myhelmapp
replicas: 4

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm! to the GIT of tedcwe'

image:
  name: devopsjourney1/mywebapp
  tag: latest