apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: osama
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
      - image: docker.io/quran/nginx:2910a4d
        name: bgd
        resources: {}
